name: CI - Site Check

on:
  push:
    branches: [ "**" ]
  pull_request:
  workflow_dispatch:

jobs:
  check-site:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Show tree
        run: |
          echo "Repo tree:"
          ls -la
          echo
          echo "Site contents:"
          ls -la site || true

      - name: Count files in site
        run: |
          echo "FILES_IN_SITE=$(find site -type f | wc -l)" >> $GITHUB_ENV
          echo "DIRS_IN_SITE=$(find site -type d | wc -l)" >> $GITHUB_ENV
      - name: Print counts
        run: |
          echo "Files: $FILES_IN_SITE"
          echo "Dirs:  $DIRS_IN_SITE"

      - name: Upload site as artifact
        uses: actions/upload-artifact@v4
        with:
          name: site-build
          path: site
